package com.dtsx.astra.cli.unit.commands;

import com.dtsx.astra.cli.commands.CommonOptions;
import com.dtsx.astra.cli.core.output.formats.OutputType;
import lombok.val;
import net.jqwik.api.*;
import picocli.CommandLine.Help.Ansi;

import java.nio.file.Path;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

// NOTE: TESTS GENERATED BY AI WITH HUMAN GUIDANCE – SORRY IN ADVANCE

@Group
public class CommonOptionsTest {
    @Group
    class merge {
        @Example
        void empty_merge_with_empty_returns_empty() {
            val empty1 = new CommonOptions();
            val empty2 = new CommonOptions();

            val result = empty1.merge(empty2);

            assertThat(result.ansi()).isEmpty();
            assertThat(result.enableSpinner()).isEmpty();
            assertThat(result.dumpLogsTo()).isEmpty();
        }

        @Property
        void this_takes_precedence_over_other_for_ansi(@ForAll Ansi thisAnsi, @ForAll Ansi otherAnsi) {
            val thisOpt = new CommonOptions(
                Optional.of(thisAnsi),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.of(otherAnsi),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.ansi()).contains(thisAnsi);
        }

        @Property
        void uses_other_when_this_is_empty_for_ansi(@ForAll Ansi otherAnsi) {
            val thisOpt = new CommonOptions(
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.of(otherAnsi),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.ansi()).contains(otherAnsi);
        }

        @Property
        void this_takes_precedence_over_other_for_outputType(@ForAll OutputType thisType, @ForAll OutputType otherType) {
            val thisOpt = new CommonOptions(
                Optional.empty(),
                Optional.of(thisType),
                Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(),
                Optional.of(otherType),
                Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.outputType()).isEqualTo(thisType);
        }

        @Property
        void uses_other_when_this_is_empty_for_outputType(@ForAll OutputType otherType) {
            val thisOpt = new CommonOptions(
                Optional.empty(),
                Optional.empty(),
                Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(),
                Optional.of(otherType),
                Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.outputType()).isEqualTo(otherType);
        }

        @Property
        void this_takes_precedence_over_other_for_verbose(@ForAll boolean thisVerbose, @ForAll boolean otherVerbose) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(),
                Optional.of(thisVerbose),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(),
                Optional.of(otherVerbose),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.verbose()).isEqualTo(thisVerbose);
        }

        @Property
        void uses_other_when_this_is_empty_for_verbose(@ForAll boolean otherVerbose) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(),
                Optional.of(otherVerbose),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.verbose()).isEqualTo(otherVerbose);
        }

        @Property
        void this_takes_precedence_over_other_for_quiet(@ForAll boolean thisQuiet, @ForAll boolean otherQuiet) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(thisQuiet),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(otherQuiet),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.quiet()).isEqualTo(thisQuiet);
        }

        @Property
        void uses_other_when_this_is_empty_for_quiet(@ForAll boolean otherQuiet) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(otherQuiet),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.quiet()).isEqualTo(otherQuiet);
        }

        @Property
        void this_takes_precedence_over_other_for_enableSpinner(@ForAll boolean thisSpinner, @ForAll boolean otherSpinner) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(thisSpinner),
                Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(otherSpinner),
                Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.enableSpinner()).contains(thisSpinner);
        }

        @Property
        void uses_other_when_this_is_empty_for_enableSpinner(@ForAll boolean otherSpinner) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(otherSpinner),
                Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.enableSpinner()).contains(otherSpinner);
        }

        @Property
        void this_takes_precedence_over_other_for_shouldDumpLogs(@ForAll boolean thisDump, @ForAll boolean otherDump) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.of(thisDump),
                Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.of(otherDump),
                Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.shouldDumpLogs()).isEqualTo(thisDump);
        }

        @Property
        void uses_other_when_this_is_empty_for_shouldDumpLogs(@ForAll boolean otherDump) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.empty(),
                Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.of(otherDump),
                Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.shouldDumpLogs()).isEqualTo(otherDump);
        }

        @Example
        void this_takes_precedence_over_other_for_dumpLogsTo() {
            val thisPath = Path.of("/tmp/logs");
            val otherPath = Path.of("/other/logs");
            
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(),
                Optional.of(thisPath),
                Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(),
                Optional.of(otherPath),
                Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.dumpLogsTo()).contains(thisPath);
        }

        @Example
        void uses_other_when_this_is_empty_for_dumpLogsTo() {
            val otherPath = Path.of("/other/logs");
            
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(),
                Optional.empty(),
                Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(),
                Optional.of(otherPath),
                Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.dumpLogsTo()).contains(otherPath);
        }

        @Property
        void this_takes_precedence_over_other_for_noInput(@ForAll boolean thisNoInput, @ForAll boolean otherNoInput) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(thisNoInput)
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(otherNoInput)
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.noInput()).isEqualTo(thisNoInput);
        }

        @Property
        void uses_other_when_this_is_empty_for_noInput(@ForAll boolean otherNoInput) {
            val thisOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.of(otherNoInput)
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.noInput()).isEqualTo(otherNoInput);
        }

        @Example
        void all_fields_present_in_this_returns_this_values() {
            val thisOpt = new CommonOptions(
                Optional.of(Ansi.ON),
                Optional.of(OutputType.JSON),
                Optional.of(true),
                Optional.of(false),
                Optional.of(true),
                Optional.of(true),
                Optional.of(Path.of("/tmp/logs")),
                Optional.of(false)
            );
            val otherOpt = new CommonOptions(
                Optional.of(Ansi.OFF),
                Optional.of(OutputType.CSV),
                Optional.of(false),
                Optional.of(true),
                Optional.of(false),
                Optional.of(false),
                Optional.of(Path.of("/other/logs")),
                Optional.of(true)
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.ansi()).contains(Ansi.ON);
            assertThat(result.outputType()).isEqualTo(OutputType.JSON);
            assertThat(result.verbose()).isTrue();
            assertThat(result.quiet()).isFalse();
            assertThat(result.enableSpinner()).contains(true);
            assertThat(result.shouldDumpLogs()).isTrue();
            assertThat(result.dumpLogsTo()).contains(Path.of("/tmp/logs"));
            assertThat(result.noInput()).isFalse();
        }

        @Example
        void all_fields_empty_in_this_returns_other_values() {
            val thisOpt = new CommonOptions();
            val otherOpt = new CommonOptions(
                Optional.of(Ansi.OFF),
                Optional.of(OutputType.CSV),
                Optional.of(false),
                Optional.of(true),
                Optional.of(false),
                Optional.of(false),
                Optional.of(Path.of("/other/logs")),
                Optional.of(true)
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.ansi()).contains(Ansi.OFF);
            assertThat(result.outputType()).isEqualTo(OutputType.CSV);
            assertThat(result.verbose()).isFalse();
            assertThat(result.quiet()).isTrue();
            assertThat(result.enableSpinner()).contains(false);
            assertThat(result.shouldDumpLogs()).isFalse();
            assertThat(result.dumpLogsTo()).contains(Path.of("/other/logs"));
            assertThat(result.noInput()).isTrue();
        }

        @Property
        void merge_does_not_modify_original_instances(@ForAll Ansi thisAnsi, @ForAll Ansi otherAnsi) {
            val thisOpt = new CommonOptions(
                Optional.of(thisAnsi),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );
            val otherOpt = new CommonOptions(
                Optional.of(otherAnsi),
                Optional.empty(), Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            // Verify originals unchanged
            assertThat(thisOpt.ansi()).contains(thisAnsi);
            assertThat(otherOpt.ansi()).contains(otherAnsi);
            assertThat(result.ansi()).contains(thisAnsi);
        }

        @Example
        void merge_with_EMPTY_constant() {
            val thisOpt = new CommonOptions(
                Optional.of(Ansi.ON),
                Optional.of(OutputType.JSON),
                Optional.empty(), Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = thisOpt.merge(CommonOptions.EMPTY);

            assertThat(result.ansi()).contains(Ansi.ON);
            assertThat(result.outputType()).isEqualTo(OutputType.JSON);
            assertThat(result.verbose()).isFalse();
        }

        @Example
        void EMPTY_merge_with_other() {
            val otherOpt = new CommonOptions(
                Optional.of(Ansi.OFF),
                Optional.of(OutputType.CSV),
                Optional.of(true),
                Optional.empty(),
                Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty()
            );

            val result = CommonOptions.EMPTY.merge(otherOpt);

            assertThat(result.ansi()).contains(Ansi.OFF);
            assertThat(result.outputType()).isEqualTo(OutputType.CSV);
            assertThat(result.verbose()).isTrue();
        }

        @Example
        void mixed_presence_selective_merge() {
            val thisOpt = new CommonOptions(
                Optional.of(Ansi.ON),
                Optional.empty(),
                Optional.of(true),
                Optional.empty(),
                Optional.empty(),
                Optional.of(true),
                Optional.empty(),
                Optional.of(false)
            );
            val otherOpt = new CommonOptions(
                Optional.empty(),
                Optional.of(OutputType.CSV),
                Optional.empty(),
                Optional.of(true),
                Optional.of(false),
                Optional.empty(),
                Optional.of(Path.of("/other/logs")),
                Optional.empty()
            );

            val result = thisOpt.merge(otherOpt);

            // From this
            assertThat(result.ansi()).contains(Ansi.ON);
            assertThat(result.verbose()).isTrue();
            assertThat(result.shouldDumpLogs()).isTrue();
            assertThat(result.noInput()).isFalse();
            
            // From other
            assertThat(result.outputType()).isEqualTo(OutputType.CSV);
            assertThat(result.quiet()).isTrue();
            assertThat(result.enableSpinner()).contains(false);
            assertThat(result.dumpLogsTo()).contains(Path.of("/other/logs"));
        }
    }
}