package com.dtsx.astra.cli.unit.commands;

import com.dtsx.astra.cli.commands.ConnectionOptions;
import com.dtsx.astra.cli.commands.ConnectionOptions.ConfigSpec;
import com.dtsx.astra.cli.commands.ConnectionOptions.CredsSpec;
import com.dtsx.astra.cli.core.config.ProfileName;
import com.dtsx.astra.cli.core.models.AstraToken;
import com.dtsx.astra.sdk.utils.AstraEnvironment;
import lombok.val;
import net.jqwik.api.Example;
import net.jqwik.api.ForAll;
import net.jqwik.api.Group;
import net.jqwik.api.Property;

import java.nio.file.Paths;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

// NOTE: TESTS GENERATED BY AI WITH HUMAN GUIDANCE – SORRY IN ADVANCE

@Group
public class ConnectionOptionsTest {
    @Group
    public class merge {
        @Example
        void empty_merge_with_empty_returns_empty() {
            val empty1 = new ConnectionOptions();
            val empty2 = new ConnectionOptions();

            val result = empty1.merge(empty2);

            assertThat(result.$config).isNull();
            assertThat(result.$creds).isNull();
        }

        @Example
        void other_takes_precedence_for_config_file() {
            val thisPath = Paths.get("/this/config");
            val otherPath = Paths.get("/other/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.empty()),
                null
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(otherPath), Optional.empty()),
                null
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(otherPath);
        }

        @Example
        void uses_this_when_other_config_file_is_empty() {
            val thisPath = Paths.get("/this/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.empty()),
                null
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.empty()),
                null
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(thisPath);
        }

        @Property
        void other_takes_precedence_for_profile_name(@ForAll ProfileName thisProfile, @ForAll ProfileName otherProfile) {
            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.of(thisProfile)),
                null
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.of(otherProfile)),
                null
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$profileName).contains(otherProfile);
        }

        @Property
        void uses_this_when_other_profile_name_is_empty(@ForAll ProfileName thisProfile) {
            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.of(thisProfile)),
                null
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.empty()),
                null
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$profileName).contains(thisProfile);
        }

        @Property
        void other_takes_precedence_for_token(@ForAll AstraToken thisToken, @ForAll AstraToken otherToken) {
            val thisOpt = new ConnectionOptions(
                null,
                new CredsSpec(thisToken, Optional.empty())
            );
            val otherOpt = new ConnectionOptions(
                null,
                new CredsSpec(otherToken, Optional.empty())
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(otherToken);
        }

        @Property
        void uses_this_when_other_token_is_null(@ForAll AstraToken thisToken) {
            val thisOpt = new ConnectionOptions(
                null,
                new CredsSpec(thisToken, Optional.empty())
            );
            val otherOpt = new ConnectionOptions(
                null,
                new CredsSpec(null, Optional.empty())
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(thisToken);
        }

        @Property
        void other_takes_precedence_for_env(@ForAll AstraEnvironment thisEnv, @ForAll AstraEnvironment otherEnv) {
            val thisOpt = new ConnectionOptions(
                null,
                new CredsSpec(null, Optional.of(thisEnv))
            );
            val otherOpt = new ConnectionOptions(
                null,
                new CredsSpec(null, Optional.of(otherEnv))
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$env).contains(otherEnv);
        }

        @Property
        void uses_this_when_other_env_is_empty(@ForAll AstraEnvironment thisEnv) {
            val thisOpt = new ConnectionOptions(
                null,
                new CredsSpec(null, Optional.of(thisEnv))
            );
            val otherOpt = new ConnectionOptions(
                null,
                new CredsSpec(null, Optional.empty())
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$env).contains(thisEnv);
        }

        @Property
        void all_config_fields_present_in_other_returns_other_values(@ForAll ProfileName thisProfile, @ForAll ProfileName otherProfile) {
            val thisPath = Paths.get("/this/config");
            val otherPath = Paths.get("/other/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.of(thisProfile)),
                null
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(otherPath), Optional.of(otherProfile)),
                null
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(otherPath);
            assertThat(result.$config.$profileName).contains(otherProfile);
        }

        @Property
        void all_creds_fields_present_in_other_returns_other_values(@ForAll AstraToken thisToken, @ForAll AstraToken otherToken, @ForAll AstraEnvironment thisEnv, @ForAll AstraEnvironment otherEnv) {
            val thisOpt = new ConnectionOptions(
                null,
                new CredsSpec(thisToken, Optional.of(thisEnv))
            );
            val otherOpt = new ConnectionOptions(
                null,
                new CredsSpec(otherToken, Optional.of(otherEnv))
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(otherToken);
            assertThat(result.$creds.$env).contains(otherEnv);
        }

        @Property
        void all_fields_empty_in_other_returns_this_values(@ForAll AstraToken thisToken, @ForAll AstraEnvironment thisEnv, @ForAll ProfileName thisProfile) {
            val thisPath = Paths.get("/this/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.of(thisProfile)),
                new CredsSpec(thisToken, Optional.of(thisEnv))
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.empty()),
                new CredsSpec(null, Optional.empty())
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(thisPath);
            assertThat(result.$config.$profileName).contains(thisProfile);
            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(thisToken);
            assertThat(result.$creds.$env).contains(thisEnv);
        }

        @Example
        void merge_does_not_modify_original_instances() {
            val thisPath = Paths.get("/this/config");
            val otherPath = Paths.get("/other/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.empty()),
                null
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(otherPath), Optional.empty()),
                null
            );

            val result = thisOpt.merge(otherOpt);

            // Verify originals unchanged
            assertThat(thisOpt.$config.$configFile).contains(thisPath);
            assertThat(otherOpt.$config.$configFile).contains(otherPath);
            assertThat(result.$config.$configFile).contains(otherPath);
        }

        @Property
        void merge_with_EMPTY_constant(@ForAll AstraToken thisToken) {
            val thisPath = Paths.get("/this/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.empty()),
                new CredsSpec(thisToken, Optional.empty())
            );

            val result = thisOpt.merge(ConnectionOptions.EMPTY);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(thisPath);
            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(thisToken);
        }

        @Property
        void EMPTY_merge_with_other(@ForAll AstraToken otherToken, @ForAll AstraEnvironment otherEnv) {
            val otherPath = Paths.get("/other/config");

            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(otherPath), Optional.empty()),
                new CredsSpec(otherToken, Optional.of(otherEnv))
            );

            val result = ConnectionOptions.EMPTY.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(otherPath);
            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(otherToken);
            assertThat(result.$creds.$env).contains(otherEnv);
        }

        @Property
        void mixed_presence_selective_merge(@ForAll AstraToken thisToken, @ForAll AstraEnvironment otherEnv, @ForAll ProfileName otherProfile) {
            val thisPath = Paths.get("/this/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.empty()),
                new CredsSpec(thisToken, Optional.empty())
            );
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.empty(), Optional.of(otherProfile)),
                new CredsSpec(null, Optional.of(otherEnv))
            );

            val result = thisOpt.merge(otherOpt);

            // From this
            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(thisPath);
            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(thisToken);

            // From other
            assertThat(result.$config.$profileName).contains(otherProfile);
            assertThat(result.$creds.$env).contains(otherEnv);
        }

        @Property
        void null_config_in_this_uses_other_config(@ForAll ProfileName otherProfile) {
            val otherPath = Paths.get("/other/config");

            val thisOpt = new ConnectionOptions(null, null);
            val otherOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(otherPath), Optional.of(otherProfile)),
                null
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(otherPath);
            assertThat(result.$config.$profileName).contains(otherProfile);
        }

        @Property
        void null_creds_in_this_uses_other_creds(@ForAll AstraToken otherToken, @ForAll AstraEnvironment otherEnv) {
            val thisOpt = new ConnectionOptions(null, null);
            val otherOpt = new ConnectionOptions(
                null,
                new CredsSpec(otherToken, Optional.of(otherEnv))
            );

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(otherToken);
            assertThat(result.$creds.$env).contains(otherEnv);
        }

        @Property
        void null_config_in_other_uses_this_config(@ForAll ProfileName thisProfile) {
            val thisPath = Paths.get("/this/config");

            val thisOpt = new ConnectionOptions(
                new ConfigSpec(Optional.of(thisPath), Optional.of(thisProfile)),
                null
            );
            val otherOpt = new ConnectionOptions(null, null);

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$config).isNotNull();
            assertThat(result.$config.$configFile).contains(thisPath);
            assertThat(result.$config.$profileName).contains(thisProfile);
        }

        @Property
        void null_creds_in_other_uses_this_creds(@ForAll AstraToken thisToken, @ForAll AstraEnvironment thisEnv) {
            val thisOpt = new ConnectionOptions(
                null,
                new CredsSpec(thisToken, Optional.of(thisEnv))
            );
            val otherOpt = new ConnectionOptions(null, null);

            val result = thisOpt.merge(otherOpt);

            assertThat(result.$creds).isNotNull();
            assertThat(result.$creds.$token).isEqualTo(thisToken);
            assertThat(result.$creds.$env).contains(thisEnv);
        }
    }
}