package com.dtsx.astra.cli.core.exceptions;

public enum CliExceptionCode {
    OK,
    USER_NOT_FOUND,
    USER_ALREADY_INVITED,
    REGION_NOT_FOUND,
    REGION_ALREADY_EXISTS,
    PROFILE_NOT_FOUND,
    KEYSPACE_NOT_FOUND,
    KEYSPACE_ALREADY_EXISTS,
    KEY_NOT_FOUND,
    ILLEGAL_OPERATION,
    FILE_ISSUE,
    EXECUTION_CANCELLED,
    TOKEN_NOT_FOUND,
    DATABASE_NOT_FOUND,
    DATABASE_ALREADY_EXISTS,
    CONFIG_ALREADY_EXISTS,
    COLLECTION_NOT_FOUND,
    COLLECTION_ALREADY_EXISTS,
    CDC_NOT_FOUND,
    CDC_ALREADY_EXISTS,
}
