package com.dtsx.astra.cli.core.exceptions;

public enum CliExceptionCode {
    ILLEGAL_OPERATION,
    CONFIG_ALREADY_EXISTS,
    DATABASE_ALREADY_EXISTS,
    KEYSPACE_ALREADY_EXISTS,
    KEYSPACE_NOT_FOUND,
    COLLECTION_ALREADY_EXISTS,
    COLLECTION_NOT_FOUND,
    CDC_ALREADY_EXISTS,
    CDC_NOT_FOUND,
    REGION_ALREADY_EXISTS,
    REGION_NOT_FOUND,
    PROFILE_NOT_FOUND,
    KEY_NOT_FOUND,
    FILE_ISSUE,
    EXECUTION_CANCELLED,
}
