name: 🌙 Nightly BUILD
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cli-tests:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      disable_tools: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - name: Test with Maven
        run: mvn compile
        
